def DRIVE (camfunc.DIRECTION, cf.DISTANCE_FRONT, cl.DISTANCE_LEFT, cr.DISTANCE_RIGHT)
	MotorL = GPIO.PWM(PIN_ENA, 50.0)
	MotorR = GPIO.PWM(PIN_ENB, 50.0)
	if (DIRECTION="RIGHT")
		
	elif (DIRECTION="LEFT")
	elif (DIRECTION="FORWARD")
	else 

